### ISSUE TITLE
Support for rowspan and colspan .

### ISSUE THREAD

**Issue by propafroz** [pofider/html-to-xlsx#10]
It would be quite good if it has support for rowspan and colspan for table layouts HTML .

Thank You,

**Comment by pofider** [comment]
I'll be busy with releasing jsreport@1.0 for couple of weeks thus have no time for this. Don't you want to try PR? Otherwise I'll possibly look at it afterwards.

**Comment by rossmartin** [comment]
@pofider Any update on this?  We really need to be able to use pivot table in our product and many excel exports end up having misaligned columns.  Thanks.

**Comment by pofider** [comment]
@rossmartin Still busy with other stuff, PR is welcome! However this package supports only simple tables, no pivots or other advanced features, are you aware of it?

**Comment by rossmartin** [comment]
@pofider Thanks for the quick response.  It is just the rowspan and colspan that is breaking our excel export of the pivot table markup.  I'm looking around to see if there is something that exists and supports html to xlsx and rowspan/colspan in tables.

**Comment by areinmeyer** [comment]
Hi, I've forked the project and have a basic working version for colspan and rowspan.  I've added some unit tests and want to do more testing before I submit a PR for this.  Any additional things that you want to see in the PR before I submit (linting, documentation, etc)?

**Comment by pofider** [comment]
@areinmeyer Great! No special requirement, just put to readme that colspan and rowspan are supported and make sure travis ci pass

**Comment by pofider** [comment]
released in 0.6.0
