### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by S1ri0S** [pofider/html-to-xlsx#13]
I've been banging my head over this for about a week now and I can't seem to find a solution.
I'm on OSX Sierra with phantomjs-prebuilt in my node_modules and I get the following error:
```
Error: connect ECONNREFUSED 127.0.0.1:49837
     at Object.exports._errnoException (util.js:1023:11)
     at exports._exceptionWithHostPort (util.js:1046:20)
     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

And this is the code:
```
let html = pug.renderFile(Utils.root('src/templates/test.pug'), { data: data });
convertToExcel(html, (err, stream) => {
  if (err) {
    console.error(err);
    throw err;
  }
  res.setHeader('Content-Type', 'application/octet-stream');
  res.setHeader('Content-Disposition', 'attachment; filename=report.xlsx');
  stream.pipe(res);
}
```

I've tried several different configurations with no success so far.
Can you provide any insight?

**Comment by pofider** [comment]
You should try to create the conversion function with these options
```js
var conversion = require("html-to-xlsx")({
  strategy: 'dedicated-process',
  phantomJSPath: require('phantomjs-prebuilt').path
});
```

However, maybe you will need to create for me  a minimal repository where I can replicate this.

**Comment by S1ri0S** [comment]
Thanks for the quick reply.
Your suggestion works but I'm wondering why I can't use 'phantom-server' strategy.
Using 'dedicated-process' seems to be really slow. I also use your other library (phantom-html-to-pdf) and I'm creating pdfs faster than I'm creating xlsx, which seems a little odd.

**Comment by pofider** [comment]
Hm, it uses the same underlying library - https://github.com/pofider/phantom-workers
So it should work the same for both.

Did you try to pass only `phantomJSPath` and keep default `strategy`?

**Comment by S1ri0S** [comment]
Yes I did and it gives me the same error as before. Could it be something with OSX Sierra and phantomjs? If so, I can live with it since production deployment will be on a linux machine where it will - hopefully - work.

**Comment by pofider** [comment]
Could be, but the phantomjs from the `require('phantomjs-prebuilt').path` should be fine.

This package has outdated `phantom-workers`, could you try to update it and try again?

**Comment by S1ri0S** [comment]
Nope. Doesn't matter what I do, whenever I use the default strategy, which is `phantom-server`, it throws the same error.

**Comment by pofider** [comment]
Hmm, I guess you will have to add some console.logs to find out if the phantomjs is crashing right after the start or it is not accepting the communication.

I've seen problems opening http connection to phantomjs previously on some corporate environments with proxy. However the problem can be somewhere completely else.

**Comment by pofider** [comment]
Can you try the same code also on windows or linux?

**Comment by S1ri0S** [comment]
I'll try it and let you know. Thanks for the help.

**Comment by S1ri0S** [comment]
So, I tried it on a Linux machine (with the same phantomjs version) and everything works as expected  so I guess it's a problem specific to OSX Sierra.

**Comment by pofider** [comment]
Thank you for info. So I guess this is for you solved, you can use dedicated process in development and production is linux anyway for you.

**Comment by S1ri0S** [comment]
Yes, that's right. You can close the issue and thanks again for the help.
