### ISSUE TITLE
Multiple rowspan not supported

### ISSUE THREAD

**Issue by areinmeyer** [pofider/html-to-xlsx#15]
In our implementation we came across a bug in the rowspan support.  It seems when multiple rowspans exist for the same row (i.e., multiple columns span multiple rows), the Excel document that is rendered either is corrupted or has cell values not in the correct order.  

I'm currently working on a fix for this, but wanted to document the issue for others and have a issue to attach to the PR.

**Comment by pofider** [comment]
Ok, great, thanks.

**Comment by bjrmatos** [comment]
thnks @areinmeyer , fixed in https://github.com/pofider/html-to-xlsx/pull/16, just need a new release from @pofider

**Comment by pofider** [comment]
Release in 0.6.4
