### ISSUE TITLE
Col Span is not working

### ISSUE THREAD

**Issue by yellareddy-allcloud** [pofider/html-to-xlsx#17]
Hello, I am trying to merge two or three columns using Colspan, it is not coming,
and i want to display in multiple table in the excel instead of showing all the data in a single table[ multiple grids in Excel], is it possible to do that one

**Comment by pofider** [comment]
Can you try if your colspan issue is fixed in the latest 0.6.4 release?

We don't support multiple sheets in the lib currently.

**Comment by bjrmatos** [comment]
closing since there was no feedback, feel free to open a new issue if you have some code to share that it is not supported
