### ISSUE TITLE
unexpected width of cell when using colspan

### ISSUE THREAD

**Issue by bjrmatos** [pofider/html-to-xlsx#19]
as reported [here](https://forum.jsreport.net/topic/285/colspan-issue-wrong-width) and with a demo available [here](https://playground.jsreport.net/studio/workspace/HykVqMIpZ/2?embed=1), the second row of excel has the first column width matching the width of the first row (one cell merged from 3 cells). since browsers does not treat this kind of content in the same way (they treat first cell of second row as something standalone from the previous row width) i would say that it is the best if we can match the browser behaviour.

**current output:**

<img width="649" alt="captura de pantalla 2017-10-19 a las 10 34 22 a m" src="https://user-images.githubusercontent.com/4262050/31779596-1bdc8f1c-b4b9-11e7-94dd-59344954293b.png">

**browser output:**

<img width="339" alt="captura de pantalla 2017-10-19 a las 10 34 07 a m" src="https://user-images.githubusercontent.com/4262050/31779604-1f2d4dc8-b4b9-11e7-904d-d3711d6f83c5.png">

**Comment by yyurko** [comment]
Could you update version of jsreport-html-to-xlsx to 1.4.4 into jsreport packege as well? Thanks.

**Comment by yyurko** [comment]
Also I have the same issue with rowspan. Could you fix it as well?

**Comment by bjrmatos** [comment]
> Could you update version of jsreport-html-to-xlsx to 1.4.4 into jsreport packege as well? Thanks.

jsreport-html-to-xlsx v1.4.4 has this change already.



> Also I have the same issue with rowspan. Could you fix it as well?

can you describe the current behavior and the expected one? if you can attach some screenshots it would be great.
