### ISSUE TITLE
Support for cell types

### ISSUE THREAD

**Issue by zheffie** [pofider/html-to-xlsx#2]
It would be great is cell types were supported. Eg. Number, text, date, ...
Currently everything is a string.

**Comment by pofider** [comment]
The problem is that in html everything is just a string.

- we can try to parse the cell values to check if it is a number or perhaps an ISO date format
- or we can add support for some attributes specifying data type like <td data-type='number'>1.1</td>

suggestions?

**Comment by zheffie** [comment]
Defining a custom html attribute is probably the way to go.

eg
```<td data-excel-format="0">100</td>````

With below format codes (from the openXML standard)
```
ID	Format Code
0	General
1	0
2	0.00
3	#,##0
4	#,##0.00
9	0%
10	0.00%
11	0.00E+00
12	# ?/?
13	# ??/??
14	mm-dd-yy
15	d-mmm-yy
16	d-mmm
17	mmm-yy
18	h:mm AM/PM
19	h:mm:ss AM/PM
20	h:mm
21	h:mm:ss
22	m/d/yy h:mm
37	#,##0 ;(#,##0)
38	#,##0 ;[Red](#,##0)
39	#,##0.00;(#,##0.00)
40	#,##0.00;[Red](#,##0.00)
45	mm:ss
46	[h]:mm:ss
47	mmss.0
48	##0.0E+0
49	@
```

**Comment by zheffie** [comment]
Problems seems to be that ```msexcel-builder``` does not really support other formats then string.
Perhaps you can incorporate following patch:
https://github.com/chuanyi/msexcel-builder/pull/11

**Comment by bjrmatos** [comment]
another options to support cell types is to use: https://github.com/d-band/better-xlsx or inspect how better-xlsx does the cell type support and extend [our fork](https://github.com/pofider/msexcel-builder)

**Comment by bjrmatos** [comment]
this is supported in `1.1.0`, docs are coming..
