### ISSUE TITLE
conversion fails when last cell of a row contains rowspan 

### ISSUE THREAD

**Issue by bjrmatos** [pofider/html-to-xlsx#21]
demo of the problem [here](https://playground.jsreport.net/studio/workspace/B1HufeIAZ/5).

the problem is mainly because this [line](https://github.com/pofider/html-to-xlsx/blob/165eeebefae67ab5a93db6f739d9ac3b45095e14/lib/conversion.js#L246), when last cell has a rowspan different than default (`1`), the `curr_row` ends with a value that points to an unexisting row. 

this can be fixed with some conditions but the bigger problem is that this case is special.

this is the browser output for this case:

<img width="202" alt="captura de pantalla 2017-10-31 a las 1 07 11 p m" src="https://user-images.githubusercontent.com/4262050/32242593-341e24b4-be41-11e7-87b5-4bc2a5803289.png">

as you can see the cells of second row starts at the position of first row, so this would require to have an special mapping of rows/cells to achieve the same behaviour of browsers.

**Comment by DKholevinsky** [comment]
I also received with the same problem
[playground](https://playground.jsreport.net/studio/workspace/Y3BG0fnPa/2335)
