### ISSUE TITLE
Custom Name For JSReport

### ISSUE THREAD

**Issue by yellareddy-allcloud** [pofider/html-to-xlsx#23]
I want to give my custom name for downloaded pdf Latest JSreport 1.8.2

**Comment by bjrmatos** [comment]
please, try to open jsreport related issues in the [main repository](https://github.com/jsreport/jsreport)

have you tried this [option](https://jsreport.net/learn/api#content-disposition-and-report-name)? you can also save the jsreport pdf result in disk with the name you prefer and then serve the file to your user.

**Comment by yellareddy-allcloud** [comment]
Hello sir, actually i am using previous version jsreport. now i upgraded, in the previous version  i am overriding AddHeader action method for custom name for downloaded reports. i am using in  C# like below code

public class MyFilterAttribute : JsReportFilterAttribute
    {
        public MyFilterAttribute(IReportingService reportingService) : base(reportingService)
        {
        }

        protected override void AddResponseHeaders(ActionExecutedContext context, EnableJsReportAttribute jsreportAttribute, Report output)
        {
            foreach (var httpResponseHeader in output.Response.Headers)
            {
                if (httpResponseHeader.Key.ToLower() == "connection" || httpResponseHeader.Key.ToLower() == "transfer-encoding")
                    continue;                

                context.HttpContext.Response.AddHeader(httpResponseHeader.Key,
                                                       string.Join(";", httpResponseHeader.Value));
            }

            foreach (var httpContentHeader in output.Response.Content.Headers)
            {
                if (httpContentHeader.Key.ToLower() == "content-disposition")
                {
                    context.HttpContext.Response.AddHeader(httpContentHeader.Key,
                        (string)context.Controller.ViewData["jsreportCustomContentDisposition"]);
                }
                else
                {
                    context.HttpContext.Response.AddHeader(httpContentHeader.Key,
                                                           string.Join(";", httpContentHeader.Value));
                }
            }

            context.HttpContext.Response.ContentType = output.ContentType.MediaType;
        }
    }

**Comment by yellareddy-allcloud** [comment]
now above code is not working, for over riding custom names after updation, can you please ping me the code related to latest version.

**Comment by bjrmatos** [comment]
ok, let's continue the issue discussion in jsreport/jsreport#358
