### ISSUE TITLE
Wrong width (multiple rows with colspan)

### ISSUE THREAD

**Issue by dniadzelka** [pofider/html-to-xlsx#24]
Hello, I applied fix for [issue about colspan](https://github.com/pofider/html-to-xlsx/issues/20) and I faced with some strange behavior.

If template contains only one row with colspan, all is fine:
![one_colspan](https://user-images.githubusercontent.com/7049736/32392342-55e70924-c0e6-11e7-9de5-e2c2f12e900a.png)

But, if template contains two row with rowspan, width is not correct:
![two_colspan](https://user-images.githubusercontent.com/7049736/32392374-797f4e8c-c0e6-11e7-86ca-db07f6b5f946.png)

Thanks in advance!

**Comment by bjrmatos** [comment]
thanks for the bug report @dniadzelka. fix is part of [jsreport-html-to-xlsx@1.4.6](https://github.com/jsreport/jsreport-html-to-xlsx/releases/tag/1.4.6). let me know if everything is ok.
