### ISSUE TITLE
Word wrap for long text

### ISSUE THREAD

**Issue by dniadzelka** [pofider/html-to-xlsx#25]
Sometimes we have so long text and we can see that heigth of cell has been changed. Do we have any way to apply word wrap?

Current behavior:
![no_word_wrap](https://user-images.githubusercontent.com/7049736/32392879-721357cc-c0e8-11e7-876a-40dee7871142.png)

Expected result:
![expected_result](https://user-images.githubusercontent.com/7049736/32392884-786421ec-c0e8-11e7-9a80-650ea49eef8f.png)

**Comment by bjrmatos** [comment]
hi! have you tried to use the `overflow` css property in the cell? that should do the trick for word wrap. i have merged that feature recently (it is also mentioned in docs).

```html
<table>
  <tr>
    <td style="overflow:scroll;">1234567789012345678912457890</td>
  </tr>
</table>
```

**Comment by dniadzelka** [comment]
Using `overflow:scroll` helps if we have multiple short words (e.g. 12324 2352453 3656456 7647).

![proof](https://user-images.githubusercontent.com/7049736/32403307-889a02ca-c147-11e7-94dc-a1f652a9090d.png)

Thanks, I will close this issue.
