### ISSUE TITLE
Add delimeter ' to the number fields

### ISSUE THREAD

**Issue by ShubhamMainali** [pofider/html-to-xlsx#27]
After converting the html to xlsx file . All the columns which holds number are added with ' delimiter which causes the problem in calculating their total in excel as it has ' so the total can't be done.
Reply me on this soon.

![delimeter](https://user-images.githubusercontent.com/26218751/33019561-e3d33072-ce20-11e7-8907-72a8329b26ca.png)

**Comment by bjrmatos** [comment]
please open the issue just once, this is a duplicated issue.. conversation moved to jsreport/jsreport-html-to-xlsx#7
