### ISSUE TITLE
conversionFactory(...)(...) is not a function

### ISSUE THREAD

**Issue by guypeled1** [pofider/html-to-xlsx#30]
i have this error when i'm trying to use the example.
what should i do?

**Comment by bjrmatos** [comment]
hi! please share the code you are using, i guess it is a bit different than the example, the module always returns a function so i don't know why you get this, maybe there is something wrong in your code

**Comment by bjrmatos** [comment]
i tried this and i can see the error, however it does not make sense because it was working at the time the example was written, looks like a V8 bug.

anyway i changed the example to this:

```js
const fs = require('fs')
const conversionFactory = require('html-to-xlsx')
const puppeteer = require('puppeteer')
const chromeEval = require('chrome-page-eval')({ puppeteer })
const conversion = conversionFactory({
  extract: chromeEval
})

async function run () {
  const stream = await conversion(`<table><tr><td>cell value</td></tr></table>`)

  stream.pipe(fs.createWriteStream('/path/to/output.xlsx'))
}

run()
```

so you can use that to test the library
