### ISSUE TITLE
AWS Lambda puppeteer

### ISSUE THREAD

**Issue by moisesrodriguez** [pofider/html-to-xlsx#33]
I've been using this package for a while on AWS Lambda on the pre 1.x version. I was looking to update my package to the latest version. But I'm having trouble with running puppeteer in AWS Lambda I've search for various solutions online but haven't found one yet that works. Was wondering if you had a possible solution or an alternative. It all started with this error:

```
Failed to launch chrome!\n/var/task/node_modules/puppeteer/
```

I've tried using `puppeteer-core`, `puppeteer-lambda` and varios other things I've found online.

**Comment by pofider** [comment]
Check this tutorial
https://jsreport.net/learn/aws-lambda-serverless

It is not exactly for this package. However, it is for the project which using this package and it shows how to run puppeteer on lambda.

Or you can keep using phantomjs even with the latest html-to-xlsx. Check the tests
https://github.com/pofider/html-to-xlsx/blob/master/test/test.js
