### ISSUE TITLE
Npm not being able to find a file

### ISSUE THREAD

**Issue by luis3199correia** [pofider/html-to-xlsx#40]
When I'm running 'npm install' cmd, got this error
![image](https://user-images.githubusercontent.com/32116636/109811542-e2c18e00-7c22-11eb-9ddb-2c81557e0a91.png)
and here I found this
![image](https://user-images.githubusercontent.com/32116636/109811622-fb31a880-7c22-11eb-807d-5736586c061c.png)
The ssh its not equals
git@github.com/pofider/html-to-xlsx.git -> ssh in error
git@github.com:pofider/html-to-xlsx.git -> ssh expected

**Comment by bjrmatos** [comment]
hi! I guess the command you are using is `npm i pofider/html-to-xlsx`, right? by looking at the error it seems that this is a problem in your machine, not having git or ssh credentials properly setup

**Comment by luis3199correia** [comment]
> hi! I guess the command you are using is `npm i pofider/html-to-xlsx`, right? by looking at the error it seems that this is a problem in your machine, not having git or ssh credentials properly setup

Hi! No, I'm running the 'npm install' command, to install all packages.
I only get this error with this package.

**Comment by bjrmatos** [comment]
it depends on the content of your `package.json`, I'm not sure why npm is trying to install the html-to-xlsx from git in the first place if you have not configured it in the first place. either check the content of your package.json and verify that there are no git dependencies there, or just try to install with `npm i html-to-xlsx`

**Comment by luis3199correia** [comment]
> it depends on the content of your `package.json`, I'm not sure why npm is trying to install the html-to-xlsx from git in the first place if you have not configured it in the first place. either check the content of your package.json and verify that there are no git dependencies there, or just try to install with `npm i html-to-xlsx`

This is our package.json
`{
	"name": "xpto",
	"version": "1.0.0",
	"license": "UNLICENSED",
	"description": "",
	"main": "src/app.ts",
	"repository":
	{
		"type": "git",
		"url": "https://our_repo/_git/xpto"
	},
	"scripts":
	{
		"start": "node --max-http-header-size=810000000 ./dist/src/app.js",
		"watch": "tsc-watch --onSuccess \"npm run start\"",
		"build": "copyfiles *.* .environment dist && tsc --project tsconfig.json",
		"build:production": "npm run build && npm prune --production",
		"eslint": "eslint --ignore-path ../.gitignore ./**/*.ts"
	},
	"dependencies":
	{
		"@types/applicationinsights": "^0.20.0",
		"@types/axios": "^0.14.0",
		"@types/body-parser": "^1.17.1",
		"@types/compression": "^1.0.1",
		"@types/copyfiles": "^2.1.1",
		"@types/cors": "^2.8.6",
		"@types/dotenv": "^8.2.0",
		"@types/express": "^4.17.2",
		"@types/express-jwt": "0.0.42",
		"@types/express-winston": "^4.0.0",
		"@types/jsreport-chrome-pdf": "^1.6.0",
		"@types/jsreport-core": "^1.5.1",
		"@types/jsreport-html-to-xlsx": "^2.0.1",
		"@types/jsreport-jsrender": "^1.0.0",
		"@types/node": "^12.12.17",
		"@types/puppeteer": "^1.19.0",
		"@types/swagger-ui-express": "^4.1.0",
		"@types/winston": "^2.4.4",
		"applicationinsights": "^1.6.0",
		"axios": "^0.19.0",
		"body-parser": "^1.19.0",
		"compression": "^1.7.4",
		"copyfiles": "^2.1.1",
		"cors": "^2.8.5",
		"dotenv": "^8.2.0",
		"express": "^5.0.0-alpha.7",
		"express-jwt": "^5.3.1",
		"express-winston": "^4.0.1",
		"html-docx-js-typescript": "^0.1.2",
		"jsreport-chrome-pdf": "^1.7.1",
		"jsreport-core": "^2.9.0",
		"jsreport-html-to-xlsx": "^2.6.0",
		"jsreport-jsrender": "^2.1.1",
		"jwks-rsa": "^1.6.0",
		"puppeteer": "^1.19.0",
		"swagger-ui-express": "^4.1.2",
		"vash": "^0.12.9",
		"winston": "^3.2.1",
		"winston-transport": "^4.3.0"
	},
	"devDependencies":
	{
		"@typescript-eslint/eslint-plugin": "^2.11.0",
		"@typescript-eslint/parser": "^2.11.0",
		"eslint": "^6.7.2",
		"eslint-config-google": "^0.14.0",
		"tsc-watch": "^4.0.0",
		"typescript": "^3.7.3"
	}
}`

**Comment by bjrmatos** [comment]
hmm i have no clue so far, it seems that your deps does not contain any git dependency, so i don't know why npm is trying to search for remote git repository in your machine, maybe you can try to remove `package-lock.json` file and then try again the `npm install`, maybe there is some git references in the lock

**Comment by luis3199correia** [comment]
> hmm i have no clue so far, it seems that your deps does not contain any git dependency, so i don't know why npm is trying to search for remote git repository in your machine, maybe you can try to remove `package-lock.json` file and then try again the `npm install`, maybe there is some git references in the lock

I removed the `package-lock.json` and still get the same error. I've tried to remove the `jsreport-html-to-xlsx` from `package.json` and when I run the `npm install` everything runs fine. So, I think, you may have something wrong in npm.

**Comment by luis3199correia** [comment]
[Solved](https://stackoverflow.com/a/65591329)
