### ISSUE TITLE
moment@2.29.3 security vulnerabilities

### ISSUE THREAD

**Issue by NLAnitha** [pofider/html-to-xlsx#42]
Hi,
  Moment 2.29.3 has a regular expression DOS security vulnerability and fix to this is available in 2.29.4. Are there plans to upgrade the version of moment used by html-to-xlsx library

https://snyk.io/vuln/npm:moment@2.29.3

**Comment by bjrmatos** [comment]
ups i forgot to comment here, yes it is fixed now, thanks for the heads up!
