### ISSUE TITLE
error : res is not defined

### ISSUE THREAD

**Issue by Vinay328** [pofider/html-to-xlsx#5]
var conversion = require ('html-to-xlsx') ();
var fs = require('fs');

fs.readFile('./Sample9.html', 'utf8', function (err,data) {

```
if (err) return console.log(err);

conversion(data,function(err,stream) {

    stream.pipe(res);

})
```

});

I am trying to read the html file(ie file name Sample9.html) place in my root directory and convert it  into xlsx , which is not happening can any one help me with this issue

**Comment by pofider** [comment]
`res` in the example is meant as the express response.Use whatever stream you have....

**Comment by bjrmatos** [comment]
closing since there is no response since many years..
